seed: 1
model: 'SPACES'
resume: true
resume_ckpt: ''
parallel: false
device_ids: [0, 1]
device: 'cuda:0'
logdir: '../output/logs'
checkpointdir: '../output/checkpoints'
evaldir: '../output/eval'

dataset: 'SpaceInvaders_seq'
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../data/ATARI'
  Riverraid_seq: '../data/Riverraid_seq'
  MontezumaRevenge_seq: '../data/MontezumaRevenge_seq'
  FishingDerby_seq: '../data/FishingDerby_seq'
  Seaquest_seq: '../data/Seaquest_seq'
  SpaceInvaders_seq: '../data/SpaceInvaders_seq'


train:
  batch_size: 2
  start_seq_length: 6
  end_seq_length: 6
  increase_seq: 5000 # Number of steps between 
  max_epochs: 1000
  max_steps: 100000
  print_every: 500
  save_every: 1000
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: False
  solver:
    fg:
      optim: 'RMSprop'
      lr: 1e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

arch:
  G: 16
  fg_sigma: 0.20

  z_pres_start_step: 10000
  z_pres_end_step: 15000
  z_pres_start_value: 0.1
  z_pres_end_value: 1e-10

  z_scale_mean_start_step: 0
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -2.0
  z_scale_mean_end_value: -2.5

  tau_start_step: 0
  tau_end_step: 10000
  tau_start_value: 2.5
  tau_end_value: 2.5

  fix_alpha_steps: 4000
  fix_alpha_value: 0.1
  boundary_loss: false
  
  recurrent_dim: 16

  K: 3
  
  bg_sigma: 0.10
gamelist: [
#    'Atlantis-v0',
#    'Asterix-v0',
#    'Carnival-v0',
#    'DoubleDunk-v0',
#    'Kangaroo-v0',
#    'MontezumaRevenge-v0',
#    'MsPacman-v0',
#    'Pooyan-v0',
#    'Qbert-v0',
    'SpaceInvaders-v0',
#    'Riverraid-v0',
    ]

